version: "3"
services:
#  postgres_2:
#    image: postgres:15
#    container_name: postgres_2
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD:   password
#      POSTGRES_DB: postgres
#      PGDATA: /data/postgres
#    volumes:
#      - ./postgres:/data/postgres
#    ports:
#      - 5433:5432
#    restart: unless-stopped


  birds:
    image: demo:v6
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5433/postgres
    ports:
      - 8080:8080
#    depends_on:
#      - postgres_2
    networks:
      - postgres_default
