version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:   password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped



  media-holder:
    image: docker.io/fldslf/media-holder:latest
 #   image: media-holder:v-1
    environment:
      DATABASE_HOST: postgres
    ports:
      - 8081:8080
    depends_on:
      - postgres




#  birds:
#    image: demo:v1
#    environment:
#      spring.datasource.url: l
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#    networks:
#      - postgres_default
