version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:   password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  birds:
    image: demo:v1
    environment:
      spring.datasource.url: l
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - postgres_default
